Update config

diff --git a/.local/bin/ssm-secret b/.local/bin/ssm-secret
--- a/.local/bin/ssm-secret
+++ b/.local/bin/ssm-secret
@@ -3,19 +3,19 @@
 # Provides a simple way to get secrets from AWS Parameter Store and securely
 # cache them locally using GNU Pass
 
-if ! pass "$1"; then
-	secret="$(aws ssm get-parameter \
-	--name "$1" \
-	--no-verify-ssl \
-	--with-decryption \
-	--output text \
-	--query Parameter.Value 2>/dev/null)"
+if ! gopass "$1"; then
+  secret="$(aws ssm get-parameter \
+    --name "$1" \
+    --no-verify-ssl \
+    --with-decryption \
+    --output text \
+    --query Parameter.Value 2>/dev/null)"
 
-	if test -z "$secret"; then
-		echo "Could not retrieve the secret from AWS"
-		exit 1;
-	fi
+  if test -z "$secret"; then
+    echo "Could not retrieve the secret from AWS"
+    exit 1
+  fi
 
-	echo "$secret" | pass add --echo "$1" >/dev/null 2>&1
-	echo "$secret"
+  echo "$secret" | gopass insert "$1"
+  echo "$secret"
 fi
